# Generated by Django 4.2 on 2023-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="persona",
            fields=[
                ("cedula", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=100, null=True)),
                ("contraseña", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
