# Generated by Django 4.2 on 2023-04-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="mascota",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("especie", models.CharField(max_length=50)),
                ("raza", models.CharField(max_length=50)),
                ("caracteristica", models.CharField(max_length=500)),
                ("peso", models.FloatField()),
                (
                    "dueño",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinaria.persona",
                    ),
                ),
            ],
        ),
    ]
