# Generated by Django 4.2.1 on 2023-05-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0003_mascota_edad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mascota",
            old_name="caracteristica",
            new_name="caracteristicas",
        ),
    ]
