# Generated by Django 4.2.1 on 2023-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0004_rename_caracteristica_mascota_caracteristicas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mascota",
            old_name="dueño",
            new_name="cedula_dueno",
        ),
    ]
