# Generated by Django 4.2.1 on 2023-05-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0005_rename_dueño_mascota_cedula_dueno"),
    ]

    operations = [
        migrations.CreateModel(
            name="facturaSINorden",
            fields=[
                ("idFactura", models.IntegerField(primary_key=True, serialize=False)),
                ("idCliente", models.IntegerField()),
                ("nombreProducto", models.CharField(max_length=50)),
                ("valor", models.FloatField()),
                ("cantidad", models.IntegerField()),
            ],
        ),
    ]
