# Generated by Django 4.2.1 on 2023-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0006_facturasinorden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="edad",
            field=models.IntegerField(default=0),
        ),
    ]
